import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Poppins, Didact_Gothic, Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
const roboto = Roboto({
  weight: ["300", "400", "500", "700", "100"],
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const didact = Didact_Gothic({
  weight: ["400"],
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
